version: '3'

services:
  # backend API
  express-ordering:
    container_name: express-ordering_backend
    build: ./
    restart: always
    working_dir: /user/src/express-ordering
    volumes:
      - ./app.js:/user/src/express-ordering/app.js
      - ./util:/user/src/express-ordering/util
      - ./database:/user/src/express-ordering/database
      - ./api:/user/src/express-ordering/api
    depends_on:
      - express-database
    env_file:
      - ./.env
    environment:
      WAIT_HOSTS: 'express-database:${MONGO_PORT}'
      MONGODB_URI: 'mongodb://${ROOT_USERNAME}:${ROOT_PASSWORD}@express-database:${MONGO_PORT}/${DATABASE_NAME}?authSource=admin'
    ports:
      - '8080:8080'
      
  # mongodb
  express-database:
    container_name: express-ordering_mongodb
    image: mongo
    restart: always
    volumes:
      - ./database/mongo-volume:/data/db
    env_file:
      - ./.env
    environment: 
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'

  # mongo express
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    depends_on:
      - express-database
    env_file:
      - ./.env
    environment:
      ME_CONFIG_MONGODB_SERVER: express-ordering_mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_LOGIN}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}
    ports:
      - "8086:8081"

  # frontend (temporarily: dev convenience purpose)
  express-frontend:
    container_name: express-ordering_frontend
    build: ./frontend
    volumes:
      - ./frontend:/user/src/express-ordering_frontend
    ports:
      - '3000:3000'

  