version: '3'

services:
  # backend API
  express-ordering:
    container_name: express-ordering_backend
    build: ./
    restart: always
    working_dir: /user/src/express-ordering
    volumes:
      - ./app.js:/user/src/express-ordering/app.js
      - ./util:/user/src/express-ordering/util
      - ./database:/user/src/express-ordering/database
      - ./api:/user/src/express-ordering/api
    depends_on:
      - express-database
    env_file:
      - ./.env
    environment:
      WAIT_HOSTS: 'express-database:${MONGO_PORT}'
      MONGODB_URI: 'mongodb://${ROOT_USERNAME}:${ROOT_PASSWORD}@express-database:${MONGO_PORT}/${DATABASE_NAME}?authSource=admin'
    ports:
      - '8080:8080'
      
  # mongodb
  express-database:
    container_name: express-ordering_mongodb
    image: mongo
    restart: always
    volumes:
      - ./database/mongo-volume:/data/db
    env_file:
      - ./.env
    environment: 
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
      
  
  